### ISSUE TITLE
IsoMutableMap entries freezing issue

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/Stately#24]
Calling `entries` returns a set of `MutableMap.MutableEntry` which apparently have a reference back to the parent map, and feezing fails. Need to create a data structure to support this.

**Comment by Dominaezzz** [comment]
https://github.com/JetBrains/kotlin-native/issues/3801

**Comment by kpgalligan** [comment]
It's not that. The mutable state kept in isolation has had `ensureNeverFrozen()` called on it, so any attempt to freeze it throws. The entry set keeps a reference to the parent. That includes each `MutableEntry` instance, so to get that to work I'd need to code an alternative to that as well.

**Comment by avently** [comment]
@kpgalligan I often see "Can't leak mutable reference" because of disabled the ability to get entries. Which is problem because many functions depend on `entries`. Once I changed maps to `sharedMutableMapOf` my app crashes in so many places.

Maybe you already invented a solution that just work? Or there is no way to make it happen?
