### ISSUE TITLE
IsoMutableMap multiple removal

### ISSUE THREAD

**Issue by omainegra** [touchlab/Stately#38]
The current `IsoMutableMap` doesn't contain a way to do multiple removals and calling `remove` multiple times turns out to be really expensive. Let's consider the following code snippet:

```kotlin
@Test
fun measure_remove_time() {
    class IsoMutableMapOptimizedForRemovals<K, V> : IsoMutableMap<K, V>() {
        fun removeAll(entries: Iterable<K>) = access { entries.forEach { remove(it) } }
    }

    val defaultMap = IsoMutableMap<Long, String>()
    val optimizedMap = IsoMutableMapOptimizedForRemovals<Long, String>()

    val elements = (1..1_000_000).map { Pair(Random.nextLong(), Random.nextLong().toString()) }

    defaultMap.putAll(elements)
    optimizedMap.putAll(elements)

    val defaultTime = measureTime {
        elements.forEach { (key, _) -> defaultMap.remove(key) }
        assertTrue { defaultMap.keys.isEmpty() }
    }

    val optimizedTime = measureTime {
        optimizedMap.removeAll(elements.map { (key, _) -> key })
        assertTrue { optimizedMap.keys.isEmpty() }
    }

    println("Default time: $defaultTime")
    println("Optimized time: $optimizedTime")
}
```

This produces the following output:

- Android
    Default time: 7.82s
    Optimized time: 148ms

- iOS Release
    Default time: 18.3s
    Optimized time: 1.59s

- iOS Debug
    Default time: 34.8s
    Optimized time: 3.76s

I also tried `defaultMap.keys.removeAll(elements.map { (key, _) -> key })` but it's even worst, for this particular example it didn't finished at all.

Does it make sense to create a PR?

**Comment by kpgalligan** [comment]
I'd rather not add methods or other classes to the collection implementations ad-hoc. The whole design of iso state allows you to easily add safe concurrent functionality, and batching calls significantly improves performance. I wrote about it, but I really need to refresh the post and link it from the repo.

https://dev.to/touchlab/kotlin-native-isolated-state-50l1

I was testing putting instead of removing, but my time diff was around an order of magnitude, similar to yours.

In this case, personally I'd do an extension function.

```kotlin
fun <K, V> IsoMutableMap<K, V>.removeAll(entries: Iterable<K>)
        = access { entries.forEach { remove(it) } }
```

I could maybe see adding some of these to the standard implementations, but need to think about it.

On the last part, is it throwing an exception or just never returning? Is the cpu spinning?

**Comment by omainegra** [comment]
Yes, an extension function could work too. For me having it could prevent performance penalties by confident developers not being aware of the underlying implementation, another reason is the difference, which is a magnitude higher.

About the third option, for a million elements it didn't finish after a couple of minutes, and CPU usage was actually low, I tested with `100_000` and this is the output
```
Default time: 825ms
Optimized time: 20.6ms
keys.removeAll time: 18.9s
```

**Comment by kpgalligan** [comment]
I see what you're saying, but what I'm saying is I'd want to think about what batch methods should look like for the whole API, if they were to be implemented. It's a maybe. I don't want to start adding them without some broader design thought.

I'm still not 100% sure iso collections is a great idea, to be honest. In most cases, I'd probably just use `IsolateState` directly and write the methods on the mutable state that I need. The `keys` and super slow time on the last thing is a good example. I implemented `key` to satisfy `MutableMap`, but doing that generically forces some bad performance. The operation you're running must somehow be adding some extra steps, which I'd still need to research. It's not spinning the CPU because it's spending a lot of time hopping threads (I would assume).

I'll think about the batch thing. Will look at the `keys` time. Looking at the code, I'm really not sure what could be adding extra operations.

**Comment by omainegra** [comment]
Yes, I understand what you're saying about the bulk operations too, is weird that `MutableCollection` contains the `removeAll` function but `MutableMap` doesn't.

About the `keys` time, something definitely weird is happening there, and after some experimentation, it doesn't seem to be related to `IsoMutableMap`

Given

```kotlin
@Test
fun measure_keys_removeAll_time() {
    val keysRemoveAll = mutableMapOf<Long, String>()
    val keysRemoveAllIso = IsoMutableMap<Long, String>()

    listOf(10, 100, 1000, 5000, 10_000, 100_000).forEach { N ->
        val elements = (1..N).map { Pair(Random.nextLong(), Random.nextLong().toString()) }
        keysRemoveAll.putAll(elements)
        keysRemoveAllIso.putAll(elements)

        val keysRemoveAllTime = measureTime {
            keysRemoveAll.keys.removeAll(elements.map { it.first })
            assertTrue { keysRemoveAll.isEmpty() }
        }

        val keysRemoveAllTimeIso = measureTime {
            keysRemoveAllIso.keys.removeAll(elements.map { it.first })
            assertTrue { keysRemoveAllIso.isEmpty() }
        }

        println("keys.removeAll     N: $N; Time: $keysRemoveAllTime")
        println("keys.removeAllIso  N: $N; Time: $keysRemoveAllTimeIso")
    }
}
```

This produces the following output

```
keys.removeAll     N: 10; Time: 9.19ms
keys.removeAllIso  N: 10; Time: 2.70ms
keys.removeAll     N: 100; Time: 395us
keys.removeAllIso  N: 100; Time: 312us
keys.removeAll     N: 1000; Time: 3.71ms
keys.removeAllIso  N: 1000; Time: 2.21ms
keys.removeAll     N: 5000; Time: 45.7ms
keys.removeAllIso  N: 5000; Time: 45.4ms
keys.removeAll     N: 10000; Time: 181ms
keys.removeAllIso  N: 10000; Time: 193ms
keys.removeAll     N: 100000; Time: 19.2s
keys.removeAllIso  N: 100000; Time: 23.8s
```

Both times are similar, and both increase a lot when the number of elements increases

**Comment by kpgalligan** [comment]
Picking this back up. Will review and make some decisions in the next couple weeks. ISO State is in flux considering the future memory model changes.
