### ISSUE TITLE
Should this foundmental infrastructure be included in Kotlin stdlib?

### ISSUE THREAD

**Issue by LanderlYoung** [touchlab/Stately#4]
Those are very foundmental Infrastructure to write concurrency code, should it be included in the kotlin standard library (including Kotlin/JVM and Kotlin/Native and so on); or the Kotlin stdlib will do some similay things?

PS: It seems that under the current K/N concurrency model, we are reinventing the java.util.concurrent class (like LinkedBlockingQueue, etc). Is that right.

**Comment by kpgalligan** [comment]
Hey, sorry I missed this. Some of this is definitely providing for functionality that exists in java.util.concurrent. Some of this will certainly wind up in libraries from Jetbrains, but unlikely in the stdlib because not all target platforms have concurrency (JS, for example). The atomic structures will wind up in Atomic-fu, for sure. The collections are a little less clear. I think the Jetbrains team intentionally doesn't implement some of the structures I'm implementing because on some level it breaks what they're trying to do with concurrency. At least they're not publishing them or promoting them. We'll see how things evolve as native gets multithreaded coroutines, and as the community evolves best practices.

**Comment by kpgalligan** [comment]
Some updated thoughts. "Relaxed mode" may make some of this obsolete, but will need shared concurrent collections. I'll be adding some implementations in the future. Stay tuned...
